# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VegetationQualityIndex
                                 A QGIS plugin
 This plugin computes the vegetation quality index
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-02-26
        copyright            : (C) 2021 by SpaceIn
        email                : spacein.io
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'SpaceIn'
__date__ = '2021-02-26'
__copyright__ = '(C) 2021 by SpaceIn'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VegetationQualityIndex class from file VegetationQualityIndex.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vegetation_quality_index import VegetationQualityIndexPlugin
    return VegetationQualityIndexPlugin()
